// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADQrH_EYPAcO8_Uys-UEJi_4x4hHer6Bk',
    appId: '1:295367907590:web:fd227c712d9effeab26687',
    messagingSenderId: '295367907590',
    projectId: 'asign-app-13da3',
    authDomain: 'asign-app-13da3.firebaseapp.com',
    storageBucket: 'asign-app-13da3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXw8SfyDW2bS6QgPMa-erZ8X_9vHnvNiU',
    appId: '1:295367907590:android:5131c5b5f9cc23a0b26687',
    messagingSenderId: '295367907590',
    projectId: 'asign-app-13da3',
    storageBucket: 'asign-app-13da3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAQzzMLumTB4nx-enYb_gBW2HFB7C7toE',
    appId: '1:295367907590:ios:da8d57f33394f0a2b26687',
    messagingSenderId: '295367907590',
    projectId: 'asign-app-13da3',
    storageBucket: 'asign-app-13da3.firebasestorage.app',
    iosBundleId: 'com.example.assignProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAQzzMLumTB4nx-enYb_gBW2HFB7C7toE',
    appId: '1:295367907590:ios:da8d57f33394f0a2b26687',
    messagingSenderId: '295367907590',
    projectId: 'asign-app-13da3',
    storageBucket: 'asign-app-13da3.firebasestorage.app',
    iosBundleId: 'com.example.assignProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADQrH_EYPAcO8_Uys-UEJi_4x4hHer6Bk',
    appId: '1:295367907590:web:a9370bd93fc36ef3b26687',
    messagingSenderId: '295367907590',
    projectId: 'asign-app-13da3',
    authDomain: 'asign-app-13da3.firebaseapp.com',
    storageBucket: 'asign-app-13da3.firebasestorage.app',
  );
}
